numbers = ([3, 1, 4, 1, 5, 9, 2])
print("What is 0 in list, {}".format(numbers[0]))
print("What is -1 in list, {}".format(numbers[-1]))
print("What is 3 in list, {}".format(numbers[3]))
print("List based on [:-1], prints", numbers[:-1])
print("List based on [3:4], prints", numbers[3:4])
print("Is 5 in numbers {}.".format(5 in numbers))
print("Is 7 in numbers {}.".format(7 in numbers))
print("Adding to list, 6, 5, 3 creates a list of",numbers + [6, 5, 3])
print("List based on [:-1], prints", numbers[2:])
print('Is "3" in numbers {}.'.format("3" in numbers))
print()
numbers = (["ten", 1, 4, 1, 5, 9, 1])
print("What is 0 in list, {}".format(numbers[0]))
print("What is -1 in list, {}".format(numbers[-1]))
print("What is 3 in list, {}".format(numbers[3]))
print("List based on [:-1], prints",numbers[:-1])
print("List based on [3:4], prints",numbers[3:4])
print("Is 5 in numbers {}.".format(5 in numbers))
print("Is 7 in numbers {}.".format(7 in numbers))
print("Adding to list, 6, 5, 3 creates a list of",numbers + [6, 5, 3])
print("List based on [2:], prints",numbers[2:])
print('Is "3" in numbers {}.'.format("3" in numbers))

